name: Test pipeline

on:
 push:
  branches:
  - master

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: setup 
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Automated Tests
      run: dotnet test -c Release --no-build
    